# Generated by Django 3.2.9 on 2022-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220312_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
