# Generated by Django 3.2.9 on 2022-02-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('buyer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.house')),
            ],
        ),
    ]
