# Generated by Django 3.2.9 on 2022-02-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_house_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table='tbl_house',
        ),
        migrations.AlterModelTable(
            name='price',
            table='tbl_price',
        ),
    ]
